### ISSUE TITLE
Not bit exact

### ISSUE THREAD

**Issue by nikishyn** [voidah/archive#10]
Hi,
This test seems to fail 
Test(-0.348907441f);

Visual Studio 2015

**Comment by voidah** [comment]
Thanks, I am able to reproduce it on vstudio 2k19, I'm working on a fix. It seems related to NaN handling on vstudio.

**Comment by voidah** [comment]
Fixed in 182de9e59ed78cd17bff16a1c487e897b044b256
Tested on linux/gcc 10.2.0 and vstudio 2k19 16.7.3

@NikishinRoman Can you test on your side please?

**Comment by nikishyn** [comment]
Hi voidah.
yes, fixed. Thanks
